//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQLBanDongHo.WebsiteQLBanDongHoDomain.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MADG { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> MATK { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> SOSAO { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
